### ISSUE TITLE
REQUIREMENTS und INSTALL Doku missing

### ISSUE THREAD

**Issue by fager** [IgnitedAndExploded/pyfire#1]
Unable to run on Debian Squeeze. tested with python 2.5, 2.6, 3.1

pls provide some information abount Software requirements

**Comment by Dr4K4n** [comment]
works well on Ubuntu 11.04 with Python 2.7.1+ (>2.7 is required).
Just start server.py with python

**Comment by jan-lugfl** [comment]
README.md contains an continually updated dependency list that is supposed to change in the development cycle..
